# ========== PostgreSQL Database Configuration ==========

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Hibernate settings
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update   # Or 'validate' / 'none' for production

# Show SQL queries in console (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable H2 console (no longer needed)
spring.h2.console.enabled=false

spring.thymeleaf.cache=false
server.port=8090
